apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: 
    - "sleep"
    - "604800"
  securityContext:
    sysctls:
    - name: net.ipv4.tcp_keepalive_time
      value: "1"
    - name: net.ipv4.tcp_keepalive_intvl
      value: "1"
    - name: net.ipv4.tcp_keepalive_probes
      value: "5"

